import Navbar from '@/components/navbar/navbar';
import './global.scss';

export const metadata = {
  title: 'Next.js project',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
